# Modified version of https://stackoverflow.com/a/66364010, licensed under CC BY-SA 4.0

name: Docker run
description: Execute docker run inside the runner

inputs:
  image:
    description: The image to use
    required: true
  entrypoint:
    description: The entrypoint
    required: false
    default: ''
  args:
    description: Arguments to pass to the entrypoint
    required: false
    default: ''
  options:
    description: Additional options to pass to docker run
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Run
      shell: bash
      run: >
        entrypoint="${{ inputs.entrypoint }}";
        docker run
        --rm
        --mount type=bind,source=${{ github.workspace }},target=${{ github.workspace }}
        ${{ inputs.options }}
        ${entrypoint:+--entrypoint="$entrypoint"}
        ${{ inputs.image }}
        ${{ inputs.args }}
