name: Lint clang-tidy for the project
author: Yuki Furuta
description: Lint clang-tidy for the project

inputs:
  path:
    description: Path to project relative from $GITHUB_WORKSPACE
    default: .
  repository_name:
    description: Name of the repository
    default: ${{ github.event.pull_request.head.repo.name }}
  pull_request_number:
    description: Number of pull request
    default: ${{ github.event.number }}
  user:
    description: Username to fetch repositories
    default: ${{ github.repository_owner }}
  token:
    description: Token to fetch repositories
    default: ${{ github.token }}

runs:
  using: docker
  image: Dockerfile
  args:
    - --working-directory=/github/workspace/${{ inputs.path }}
    - --clang-tidy
    - --clang-tidy-yaml-dir=/github/workspace/clang-tidy-results
  env:
    CIRCLE_PULL_REQUEST: true
    CIRCLE_PROJECT_USERNAME: ${{ inputs.user }}
    CIRCLE_PROJECT_REPONAME: ${{ inputs.repository_name }}
    CIRCLE_PR_NUMBER: ${{ inputs.pull_request_number }}
    GITHUB_ACCESS_TOKEN: ${{ inputs.token }}
    PYTHONUNBUFFERED: x
