name: Test catkin workspace
author: Yuki Furuta
description: Test software stack using catkin test

inputs:
  ros_distro:
    description: ROS version
    required: false
    default: noetic
  catkin_workspace:
    description: Path to catkin workspace relative to $GITHUB_WORKSPACE
    required: false
    default: .
  user:
    description: Username to fetch repositories
    default: ${{ github.repository_owner }}
  token:
    description: Token to fetch repositories
    default: ${{ github.token }}
  catkin_test_targets:
    description: Target packages to be tested
    default: project
  catkin_test_args:
    description: Arguments to run catkin test with
    default: --verbose --interleave-output --no-status --no-notify --summarize

runs:
  using: composite
  steps:
    - name: Setup git config
      uses: ./setup_git
      with:
        user: ${{ inputs.user }}
        token: ${{ inputs.token }}
    - name: Test catkin workspace
      run: /test_catkin_workspace.sh
      shell: bash
      env:
        ROS_DISTRO: ${{ inputs.ros_distro }}
        CATKIN_WORKSPACE: ${{ inputs.catkin_workspace }}
        CATKIN_TEST_TARGETS: ${{ inputs.catkin_test_targets }}
        CATKIN_TEST_ARGS: ${{ inputs.catkin_test_args }}
        TERM: xterm-256color
    - name: List test results
      if: success() || failure()
      id: list_test_results
      continue-on-error: true
      run: |
        cd ${{ inputs.catkin_workspace }}
        find . -iwholename "./build/*/test_results/**/*.xml" | grep .
      shell: bash
    - name: Test report
      uses: dorny/test-reporter@v1
      if: (success() || failure()) && steps.list_test_results.outcome == 'success'
      continue-on-error: true
      with:
        name: Tests
        path: "${{ github.workspace }}/${{ inputs.catkin_workspace }}/build/*/test_results/**/*.xml"
        reporter: java-junit
        working-directory: "${{ inputs.catkin_workspace }}/src/project"
        fail-on-error: false
