name: Setup catkin workspace
author: Yuki Furuta
description: Prepare catkin workspace

inputs:
  ros_distro:
    description: ROS version
    required: false
    default: noetic
  catkin_workspace:
    description: Path to catkin workspace relative to $GITHUB_WORKSPACE
    required: false
    default: .
  catkin_extend:
    description: Path to extending catkin workspace
    required: false
    default: ''
  rosinstall_file:
    description: Path to .rosinstall file of the project
    required: false
    default: .rosinstall
  deps_rosinstall_file:
    description: Path to .rosinstall file of the dependencies of the project
    required: false
    default: .rosinstall
  project_name:
    description: Path to the directory to setup workspace from
    required: false
    default: project
  user:
    description: Username to fetch repositories
    default: ${{ github.repository_owner }}
  token:
    description: Token to fetch repositories
    default: ${{ github.token }}
  # cache
  cache_source_space:
    description: Enable caching source workspace
    default: true
  cache_source_space_id:
    description: Id for source space cache
    default: '${{ github.action }}_source'
  cache_remote_path:
    description: Remote path to use for uploading/downloading cache
    default: ''

runs:
  using: composite
  steps:
    - name: Setup git config
      uses: GITAI/github-actions/setup_git@main
      with: 
        user: ${{ inputs.user }}
        token: ${{ inputs.token }}
    - name: Load source cache
      if: ${{ inputs.cache_source_space != 'false' }}
      uses: GITAI/github-actions/cache@main
      with:
        method: load
        key: ${{ inputs.cache_source_space_id }}
        path: ${{ inputs.catkin_workspace }}/src
        remote_path: ${{ inputs.cache_remote_path }}
    - name: Setup catkin workspace
      run: /setup_catkin_workspace.sh
      shell: bash
      env:
        ROS_DISTRO: ${{ inputs.ros_distro }}
        CATKIN_WORKSPACE: ${{ inputs.catkin_workspace }}
        CATKIN_EXTEND: ${{ inputs.catkin_extend }}
        ROSINSTALL_FILE: ${{ inputs.rosinstall_file }}
        DEPS_ROSINSTALL_FILE: ${{ inputs.deps_rosinstall_file }}
        TERM: xterm-256color
        PROJECT_NAME: ${{ inputs.project_name }}
    - name: Save source cache
      if: ${{ inputs.cache_source_space != 'false' }}
      id: cache_source_space
      uses: GITAI/github-actions/cache@main
      with:
        method: save
        key: ${{ inputs.cache_source_space_id }}
        path: ${{ inputs.catkin_workspace }}/src
        remote_path: ${{ inputs.cache_remote_path }}
        exclude: '${{ inputs.project_name }}/**'
