name: Build catkin workspace
author: Yuki Furuta
description: Build software stack using catkin build

inputs:
  ros_distro:
    description: ROS version
    required: false
    default: noetic
  catkin_workspace:
    description: Path to catkin workspace relative to $GITHUB_WORKSPACE
    required: false
    default: .
  catkin_extend:
    description: Path to extending catkin workspace
    required: false
    default: ''
  user:
    description: Username to fetch repositories
    default: ${{ github.repository_owner }}
  token:
    description: Token to fetch repositories
    default: ${{ github.token }}
  ccache_storage_size:
    description: Storage size for ccache
    default: 5G
  cmake_build_type:
    description: Build type of cmake
    default: RelWithDebInfo
  cmake_args:
    description: Optional arguments passed to cmake
    default: ''
  catkin_build_targets:
    description: Target packages to be built
    default: project
  catkin_build_args:
    description: Arguments to run catkin build with
    default: --limit-status-rate 0.0017 --summarize
  catkin_install:
    description: Enable catkin install workspace
    default: true
  # cache
  cache_build_space:
    description: Enable caching build workspace
    default: true
  cache_build_space_id:
    description: Id for build space cache
    default: '${{ github.action }}_build'
  cache_devel_space:
    description: Enable caching devel workspace
    default: true
  cache_devel_space_id:
    description: Id for devel space cache
    default: '${{ github.action }}_devel'
  cache_remote_path:
    description: Remote path to use for uploading/downloading cache
    default: ''

runs:
  using: composite
  steps:
    - name: Setup git config
      uses: GITAI/github-actions/setup_git@main
      with:
        user: ${{ inputs.user }}
        token: ${{ inputs.token }}
    - name: Setup ccache
      run: |
        [[ "$(which ccache)" != "" ]] || apt-get install -qq -y ccache
        ccache -M ${{ inputs.ccache_storage_size }}
        ccache -o compression=true
        ccache -o sloppiness=file_macro,time_macros
      shell: bash
    - name: Load build cache
      if: ${{ inputs.cache_build_space != 'false' }}
      uses: GITAI/github-actions/cache@main
      with:
        method: load
        key: ${{ inputs.cache_build_space_id }}
        path: ${{ inputs.catkin_workspace }}/build
        remote_path: ${{ inputs.cache_remote_path }}
    - name: Load devel cache
      if: ${{ inputs.cache_devel_space != 'false' }}
      uses: GITAI/github-actions/cache@main
      with:
        method: load
        key: ${{ inputs.cache_devel_space_id }}
        path: ${{ inputs.catkin_workspace }}/devel
        remote_path: ${{ inputs.cache_remote_path }}
    - name: Build catkin workspace
      run: /build_catkin_workspace.sh
      shell: bash
      env:
        ROS_DISTRO: ${{ inputs.ros_distro }}
        CATKIN_WORKSPACE: ${{ inputs.catkin_workspace }}
        CATKIN_EXTEND: ${{ inputs.catkin_extend }}
        CMAKE_BUILD_TYPE: ${{ inputs.cmake_build_type }}
        CMAKE_ARGS: ${{ inputs.cmake_args }}
        CATKIN_BUILD_TARGETS: ${{ inputs.catkin_build_targets }}
        CATKIN_BUILD_ARGS: ${{ inputs.catkin_build_args }}
        CATKIN_INSTALL: ${{ inputs.catkin_install }}
        TERM: xterm-256color
    - name: Save build cache
      if: ${{ inputs.cache_build_space != 'false' }}
      id: cache_build_space
      uses: GITAI/github-actions/cache@main
      with:
        method: save
        key: ${{ inputs.cache_build_space_id }}
        path: ${{ inputs.catkin_workspace }}/build
        exclude: '**/test_results/**'
        remote_path: ${{ inputs.cache_remote_path }}
    - name: Save devel cache
      if: ${{ inputs.cache_devel_space != 'false' }}
      id: cache_devel_space
      uses: GITAI/github-actions/cache@main
      with:
        method: save
        key: ${{ inputs.cache_devel_space_id }}
        path: ${{ inputs.catkin_workspace }}/devel
        remote_path: ${{ inputs.cache_remote_path }}
